gui:
  theme:
    selectedLineBgColor:
      - '#1e3260'
    selectedRangeBgColor:
      - '#1e3260'

customCommands:
  - key: 'o'
    context: 'files'
    command: '[ -n "$NVIM" ] && nvim --server "$NVIM" --remote-tab "{{.SelectedFile.Name}}" || nvim "{{.SelectedFile.Name}}"'
    description: 'Open file in a new nvim tab'
